services:
  ollama2:
    image: ollama/ollama:latest
    container_name: ollama2
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - app_network


# test runner on compose/start
  test:
    build: .
    container_name: test_runner
    working_dir: /app
    command: python -m pytest -q --disable-warnings --maxfail=1
    volumes:
      - .:/app
      - ./test/tiny_scripts:/app/test/tiny_scripts
      - ./test/fixtures:/app/test/fixtures
      - ./test/data:/app/test/data
    environment:
      - OLLAMA_HOST=http://ollama2:11434
    depends_on:
      app_database:
        condition: service_healthy
      ollama2:
        condition: service_started
    networks:
      - app_network
    restart: "no"


      # waits for the tests to resolve

  app:
    build: .
    container_name: desktop_app # container name
    working_dir: /app
    command: python -m src.cli.main
      
    environment:
      - OLLAMA_HOST=http://ollama2:11434
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # For GUI on Linux/Mac
      - .:/app
    networks:
      - app_network
    stdin_open: true
    tty: true

volumes:
  ollama_data:
    driver: local

networks:
  app_network:
        driver: bridge