services:

# test runner on compose/start
  test:
    build: .
    container_name: test_runner
    working_dir: /app
    command: python -m pytest -q --disable-warnings
    volumes:
      - .:/app
      - ./test/tiny_scripts:/app/test/tiny_scripts
      - ./test/fixtures:/app/test/fixtures
      - ./test/data:/app/test/data
    environment:
      - DB_HOST=app_database
      - DB_PORT=3306
    depends_on:
      app_database:
        condition: service_healthy
    networks:
      - app_network
    restart: "no"


      # waits for the tests to resolve

  app:
    build: .
    container_name: desktop_app # container name
    working_dir: /app
    command: python -m src.cli.main
      
    environment:
      - DISPLAY=${DISPLAY}
      - DATABASE_URL=mysql+mysqlconnector://appuser:apppassword@app_database:3306/appdb
      - DB_HOST=app_database
      - DB_USER=appuser
      - DB_PASSWORD=apppassword
      - DB_NAME=appdb
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # For GUI on Linux/Mac
      - .:/app
    networks:
      - app_network
    stdin_open: true
    tty: true

volumes:
  mysql_data:
    driver: local

networks:
  app_network:
        driver: bridge